name = "HTbin"
uuid = "eccd6b31-e9c6-458b-a2ad-a886a9ef1267"
authors = ["htyeim <htyeim@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
